# Generated by Django 5.2.6 on 2026-01-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0005_matricula_progresso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_verificacao', models.CharField(db_index=True, max_length=32, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('link_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('id_trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='onboarding_app.trilha')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-data_emissao'],
                'unique_together': {('id_usuario', 'id_trilha')},
            },
        ),
    ]
