# Generated by Django 5.2.6 on 2026-01-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0006_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='modo_visualizacao',
            field=models.BooleanField(default=False, help_text='Se True, usuário pode apenas visualizar (sem registrar novo progresso)'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='permite_refazer',
            field=models.BooleanField(default=False, help_text='Se True, admin pode refazer a trilha mantendo histórico'),
        ),
    ]
