# Generated by Django 5.2.6 on 2026-02-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_app', '0004_notification_notificationpreference'),
        ('onboarding_app', '0007_matricula_modo_visualizacao_and_more'),
    ]

    operations = [
    ]
