# Generated by Django 5.2.6 on 2025-12-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
