# Generated by Django 5.2.6 on 2026-02-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_setor_subsetor_user_campos_obrigatorios'),
        ('users', '0005_remove_user_avatar_delete_enrollment'),
    ]

    operations = [
    ]
